# Generated by Django 4.2.11 on 2024-04-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_portal', '0003_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserData',
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
