# Generated by Django 4.2.11 on 2024-04-09 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_portal', '0004_delete_userdata_alter_timeslot_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
