# Generated by Django 4.2.11 on 2024-04-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer_portal', '0005_alter_timeslot_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='LugarEstadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha', models.CharField(max_length=20)),
                ('coluna', models.CharField(max_length=20)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
